### ISSUE TITLE
JMG 1.8存在jvm适配问题

### ISSUE THREAD

**Issue by cvdv123** [pen4uin/java-memshell-generator#17]
[*] Attaching to target JVM with PID: 8928
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at TomcatAgentTransformer.attachAgentToTargetJvm(TomcatAgentTransformer.java:186)
        at TomcatAgentTransformer.main(TomcatAgentTransformer.java:151)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at TomcatAgentTransformer.attachAgentToTargetJvm(TomcatAgentTransformer.java:179)
        ... 1 more
Caused by: com.sun.tools.attach.AttachNotSupportedException: Unable to attach to 32-bit process running under WOW64
        at sun.tools.attach.WindowsVirtualMachine.openProcess(Native Method)
        at sun.tools.attach.WindowsVirtualMachine.<init>(WindowsVirtualMachine.java:56)
        at sun.tools.attach.WindowsAttachProvider.attachVirtualMachine(WindowsAttachProvider.java:69)
        at io.earcam.wrapped.com.sun.tools.attach.Provider.attachVirtualMachine(Provider.java:74)
        at com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)
        ... 6 more

**Comment by pen4uin** [comment]
你看看目标进程用的 jdk 和你 attach 用的 jdk 是不是同一个

**Comment by yu2lulu** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.024 s
[INFO] Finished at: 2024-06-05T14:34:41+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project jmg-gui: Could not resolve dependencies for project jmg:jmg-gui:jar:1.0.8: The following artifacts could not be resolved: jmg:jmg-core:jar:1.0.8, me.gv7.woodpecker:jexpr-encoder-utils:jar:0.2.2, jmg:jmg-behinder:jar:1.0.8, jmg:jmg-antsword:jar:1.0.8, jmg:jmg-godzilla:jar:1.0.8, jmg:jmg-suo5:jar:1.0.8, jmg:jmg-neoregeorg:jar:1.0.8, jmg:jmg-custom:jar:1.0.8: Could not find artifact jmg:jmg-core:jar:1.0.8 in alimaven (http://maven.aliyun.com/nexus/content/groups/public/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
